configured_endpoints: 3
openapi_spec_url: https://storage.googleapis.com/stainless-sdk-openapi-specs/liquidmetal-ai%2Fraindrop-19a079f994cdfe3fdc45c9653d072c7841ccf231cadf82f6fc1c100a1f12c4d0.yml
openapi_spec_hash: 5ff2ef8accff2b7cdd8cfe159f08b9dd
config_hash: d9f62d6a572e95aabf8729754bd5cb65
