configured_endpoints: 17
openapi_spec_url: https://storage.googleapis.com/stainless-sdk-openapi-specs/liquidmetal-ai%2Fraindrop-e686a4d75dfecf3888945de9de4c4515c5c308e8c5cf6d8b302a936cce69fde4.yml
openapi_spec_hash: efd284ad376b750dfae2338b053bb633
config_hash: 9ecad08e6ebdf0d32b8e8e7c6987ac7f
